<a href="https://colab.research.google.com/github/rktn0905/Tensorflow101/blob/main/HiddenLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hidden Layer**

In [95]:
import tensorflow as tf
import pandas as pd

In [96]:
#데이터 준비
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file)
print(boston.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [97]:
#독립 변수, 종속 변수
x_var = boston [['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
y_var = boston[['medv']]
print(x_var.shape,y_var.shape)

(506, 13) (506, 1)


In [98]:
#모델
x = tf.keras.layers.Input(shape=[13])
h = tf.keras.layers.Dense(10,activation='swish')(x)
y = tf.keras.layers.Dense(1)(h)
model = tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [99]:
#모델 확인
model.summary()

Model: "model_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_46 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_47 (Dense)             (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [100]:
#학습
model.fit(x_var,y_var,epochs=200,verbose=0)

In [101]:
#모델을 이용해 봅시다
print(model.predict(x_var[:5]))
print(y_var[:5])

[[28.035046]
 [25.85571 ]
 [28.919716]
 [30.548592]
 [29.642275]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [102]:
#데이터 준비
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file)
print(iris.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [103]:
#원핫인코딩
incoding = pd.get_dummies(iris)
print(incoding)

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]


In [104]:
#독립 변수, 종속 변수
x_var = incoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_var = incoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(x_var.shape,y_var.shape)

(150, 4) (150, 3)


In [116]:
#모델
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8,activation='swish')(x)
h1 = tf.keras.layers.Dense(8,activation='swish')(h)
h2 = tf.keras.layers.Dense(8,activation='swish')(h1)
y = tf.keras.layers.Dense(3, activation='softmax')(h2)
model = tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [117]:
#학습
model.fit(x_var,y_var,epochs=1000,verbose=0)

In [118]:
# 모델 구조 확인
model.summary()

Model: "model_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        [(None, 4)]               0         
_________________________________________________________________
dense_64 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_65 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_66 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_67 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [120]:
#모델을 이용해 봅시다
print(model.predict(x_var[0:5]))
print(y_var[0:5])

[[9.9999678e-01 3.1737184e-06 6.1973468e-13]
 [9.9999535e-01 4.6056844e-06 2.3413415e-12]
 [9.9999547e-01 4.5496577e-06 2.6397818e-12]
 [9.9999440e-01 5.6190406e-06 4.0318365e-12]
 [9.9999678e-01 3.2239459e-06 6.6335815e-13]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
